FROM nginx

COPY ./config/sites-enabled /etc/nginx/sites-enabled
COPY ./config/sites-enabled /etc/nginx/sites-available
COPY ./config/includes /etc/nginx/includes
COPY ./config/nginx.conf /etc/nginx/nginx.conf