# -*- mode: ruby -*-
# vi: set ft=ruby :

unless Vagrant.has_plugin?("vagrant-docker-compose")
  system("vagrant plugin install vagrant-docker-compose")
  puts "Dependencies installed, please try the command again."
  exit
end

Vagrant.configure("2") do |config|
    config.vm.provider "parallels" do |vb|
        vb.name = 'howtocodewell-code-quiz'
        vb.memory = 4000
        vb.cpus = 2
    end

    config.vm.network "public_network", ip: "192.168.1.200"
    config.vm.synced_folder "./", "/home/vagrant/api"
    config.vm.box = "bento/debian-10"
    config.vm.network "private_network", type: "dhcp"

    config.vm.provision :docker
    config.vm.provision :docker_compose, yml: "/home/vagrant/api/docker-compose.yml", rebuild: true, run: "always", compose_version: "v2.10.2"

end
